### ISSUE TITLE
Parameters default value is not working

### ISSUE THREAD

**Issue by code-vj** [dotarj/PartialResponse#1]
I am trying to set default fields by setting default value of fields parameter, see below code, this code not working and ignoring it and returning all fields. 

`[Route("")]
        [HttpGet]
        public HttpResponseMessage GetAllLoginThemes(string Key, string Secret, string fields = "Data(Name,Title,IsPaid)")
        {

```
    }`
```

**Comment by dotarj** [comment]
PartialResponse operates on the values in the query string (HttpRequestMessage.RequestUri.Query), so adding a parameter 'fields' with default values will not work.
