### ISSUE TITLE
empty array is removed from json response

### ISSUE THREAD

**Issue by xalikoutis** [dotarj/PartialResponse#11]
Hi congrats for the great work,

so my problem is in my web api where all my request respond the following structure
```
{
totalCount:12,
data[....]
}
```
When the are no data 
```
{
totalCount:0,
data[]
}
```

and apply fields=totalcount,data(field1,field2)
then i get a response with data[] removed

```
{
totalCount:0
}
```

thats a problem because it cannot be mapped properly on the client

**Comment by dotarj** [comment]
Hi, can you please let me know which version of the package you're using: WebApi.PartialResponse or PartialResponse.AspNetCore.Mvc.Formatters.Json?

**Comment by vhatsura** [comment]
Hi, @dotarj!
We faced with the same issue. We are using WebApi.PartialResponse 0.1.4 version

**Comment by dotarj** [comment]
Hi @vhatsura, thanks for the info. The current implementation removes an array if it becomes empty after filtering fields, but this also happens if the array was already empty. I'll try to figure out a solution to the problem.

**Comment by dotarj** [comment]
I've pushed a new version of WebApi.PartialResponse which does not remove an array if it was already empty: https://www.nuget.org/packages/WebApi.PartialResponse/1.0.0-beta3.
