### ISSUE TITLE
Don't apply fields deletion when request is not successful

### ISSUE THREAD

**Issue by vhatsura** [dotarj/PartialResponse#17]
Hi,

So my problem is when my web api returns 400 Bad request code (one of parameter is invalid). In this case I return message in response with description of error. But PartialResponse cut this field (in mu case field is called 'Message').
As a workaround I can specify Message field in 'fields' parameter of request, but it isn't pretty from code perspective.

Is there any possibility to configure PartialResponse to skip deletion of fields in such cases?

**Comment by dotarj** [comment]
Hi @vhatsura, do you use Microsoft.Owin.Hosting for hosting your ASP.NET Web API application?

**Comment by vhatsura** [comment]
@dotarj, we are using HttpSelfHostServer for hosting Web API application

**Comment by dotarj** [comment]
Getting the response status code in a media type formatter is difficult as it has no access to the current response, only the current request. PartialJsonMediaTypeFormatter tries to get the HttpContext from the HttpRequestMessage.Properties (the framework adds it to the dictionary using the key “MS_HttpContext”), which is used to determine the response status code. The fields parameter is applied if the status code is 200 or if HttpContext is not found in the HttpRequestMessage.Properties.

It seems that the HttpContext is not set when using HttpSelfHost or OwinHost, so in that case the fields parameter is always applied. I'm preparing a work around by providing middleware (an action filter) which puts the HttpResponseMessage in the HttpRequestMessage.Properties so it can be accessed from the media type formatter. Not sweet but I don't see another solution right now. I'll keep you posted.

**Comment by dotarj** [comment]
A new version of WebApi.PartialResponse is released which bypasses fields filtering when the response status code is not 200 when using OwinHost or HttpSelfHost: https://www.nuget.org/packages/WebApi.PartialResponse/1.0.0-beta4. You need to register an additional filter to enable this feature:

`configuration.Filters.Add(new PartialJsonActionFilter());`

An example of the enabled feature can be found in the samples project: https://github.com/dotarj/PartialResponse/tree/master/samples/PartialResponse.Demo.

**Comment by vhatsura** [comment]
Hi @dotarj!
When are you going to release stable version?

**Comment by dotarj** [comment]
Hi @vhatsura! I'm currently working on a reliable way to build, test and deploy PartialResponse using AppVeyor instead of building, testing and deploying by hand. I will soon release a new version, build using the new build pipeline. I'll let you know.

**Comment by vhatsura** [comment]
Great news, thanks!)
I close this issue due to it was fixed.

**Comment by dotarj** [comment]
Hi @vhatsura! The stable version is released to NuGet: https://www.nuget.org/packages/WebApi.PartialResponse. Please let me know if you encounter any problems.
