### ISSUE TITLE
Make GetPartialResponseFields a public method

### ISSUE THREAD

**Issue by RobbyDeLaet** [dotarj/PartialResponse#2]
In my WebApi projects I would like to build SQL Queries that return only the partial response fields.
Is it possible to make the GetPartialResponseFields "public", so that I can use the fields in the returned collection?

**Comment by dotarj** [comment]
The method could be public, but do realize that the given fields are not validated against the resulting DTO, so could contain fields that are not part of the DTO. Did you take a look at ASP.NET Web API 2 OData? The $select parameter provides similar functionality and it even can generate dynamic SQL containing just the requested fields. Please let me know if you're sure that making the method public is the desired solution.

**Comment by RobbyDeLaet** [comment]
Hi Arjen,

Thanks for the quick response. I will first look at the suggested OData
solution. I will let you now if making the method public is still necessary.

Cheers,
Robby

---

Robby De Laet
zaakvoerder

SOMMICO b.v.b.a.
Ketelstraat 14
1982 - Weerde (Zemst)

www.sommico.com

+32 495 57 19 81
robby@sommico.com

2016-02-18 20:20 GMT+01:00 Arjen Post notifications@github.com:
