### ISSUE TITLE
AspNetCore support

### ISSUE THREAD

**Issue by carl-thomas** [dotarj/PartialResponse#4]
You have a feature branch feature/aspnetcore. When are you planning on releasing this as a stable package? Or are you planning on releasing a pre-release package? This is perfect for what I need but I need a AspNetCore nuget package. Thanks

**Comment by dotarj** [comment]
I expect to release a pre-release package on NuGet within a week and a stable version not much later. I'll keep you posted.

**Comment by dotarj** [comment]
I've created a beta version of the package: https://www.nuget.org/packages/PartialResponse.AspNetCore.Mvc.Formatters.Json/. There is no updated documentation yet, but you can check the samples to get you started (https://github.com/dotarj/PartialResponse/tree/feature-aspnetcore/samples/PartialResponse.AspNetCore.Mvc.Demo). Please let me know if you have trouble getting it running.

**Comment by carl-thomas** [comment]
Thanks for getting this prerelease live so soon. I have noticed you are using DotNet Core v1.1.0. I am currently using the LTS version 1.0.1 and cannot upgrade yet. Is there anyway you could downgrade the dependencies to 1.0.1? Thanks

**Comment by dotarj** [comment]
Do you mean the reference to Microsoft.AspNetCore.Mvc.Core? Other than that, only NETStandard.Library and Newtonsoft.Json are referenced. Only the test and sample projects target netcoreapp1.1 and depend on Microsoft.NETCore.App 1.1.0.  I've downgraded the Microsoft.AspNetCore.Mvc.Core reference from 1.1.0 to 1.0.1 (ea49d243753995486288c305bc1ad333fd539214) and will push a new release tomorrow.

**Comment by dotarj** [comment]
Hi Carl, version 1.0.0 of PartialResponse.AspNetCore.Mvc.Formatters.Json has been released some time ago. I'll close this issue now. Please let me know if you have any other questions.
