### ISSUE TITLE
asp.net core 2.0

### ISSUE THREAD

**Issue by jasonraynor** [dotarj/PartialResponse#8]
The below exception is being thrown when using the PartialResponse.AspNetCore.Mvc.Formatters.Json package in asp.net core 2.0

> MissingMethodException: Method not found: 'Microsoft.Net.Http.Headers.MediaTypeHeaderValue Microsoft.Net.Http.Headers.MediaTypeHeaderValue.Parse(System.String)'
PartialResponse.AspNetCore.Mvc.Formatters.Json.Internal.MvcPartialJsonMvcOptionsSetup.Configure(MvcOptions options)
Microsoft.Extensions.Options.OptionsFactory.Create(string name)
Microsoft.Extensions.Options.OptionsManager+<>c__DisplayClass5_0.<Get>b__0()
System.Lazy.ViaFactory(LazyThreadSafetyMode mode)
System.Lazy.ExecutionAndPublication(LazyHelper executionAndPublication, bool useDefaultConstructor)
System.Lazy.CreateValue()
Microsoft.Extensions.Options.OptionsCache.GetOrAdd(string name, Func<TOptions> createOptions)
Microsoft.Extensions.Options.OptionsManager.Get(string name)
Microsoft.Extensions.Options.OptionsManager.get_Value()
Microsoft.AspNetCore.Mvc.Internal.DefaultApplicationModelProvider..ctor(IOptions<MvcOptions> mvcOptionsAccessor)
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

**Comment by dotarj** [comment]
Thanks for submitting the issue. The issue is fixed (#10) and new version of PartialResponse.AspNetCore.Mvc.Formatters.Json is available: [2.0.0](https://github.com/dotarj/PartialResponse/releases/tag/2.0.0).
